// Brand data with dummy image paths
// Replace these with your actual 30+ brand images

export const brandList = [
  // First set of dummy brand images
  { id: '2', name: 'Brand 2', image: '/images/brands/brand2.avif' },
  { id: '3', name: 'Brand 3', image: '/images/brands/brand3.avif' },
  { id: '4', name: 'Brand 4', image: '/images/brands/brand4.avif' },
  { id: '5', name: 'Brand 5', image: '/images/brands/brand5.avif' },
  { id: '6', name: 'Brand 6', image: '/images/brands/brand6.avif' },
  { id: '7', name: 'Brand 7', image: '/images/brands/brand7.avif' },
  { id: '8', name: 'Brand 8', image: '/images/brands/brand8.avif' },
  { id: '9', name: 'Brand 9', image: '/images/brands/brand9.avif' },
  { id: '10', name: 'Brand 10', image: '/images/brands/brand10.avif' },
  { id: '11', name: 'Brand 11', image: '/images/brands/brand11.avif' },
  { id: '12', name: 'Brand 12', image: '/images/brands/brand12.avif' },
  { id: '13', name: 'Brand 13', image: '/images/brands/brand13.png' },
  { id: '14', name: 'Brand 14', image: '/images/brands/brand14.avif' },
  { id: '15', name: 'Brand 15', image: '/images/brands/brand15.png' },
  { id: '16', name: 'Brand 16', image: '/images/brands/brand16.jpg' },
  { id: '17', name: 'Brand 17', image: '/images/brands/brand17.jpg' },
  { id: '18', name: 'Brand 18', image: '/images/brands/brand18.jpg' },
  { id: '1', name: 'Brand 1', image: '/images/brands/brand1.webp' },
  { id: '19', name: 'Brand 19', image: '/images/brands/brand19.jpg' },
  { id: '20', name: 'Brand 20', image: '/images/brands/brand20.jpg' },
  { id: '21', name: 'Brand 21', image: '/images/brands/brand21.jpg' },
  { id: '22', name: 'Brand 22', image: '/images/brands/brand22.jpg' },
  { id: '23', name: 'Brand 23', image: '/images/brands/brand23.jpg' },
  { id: '24', name: 'Brand 24', image: '/images/brands/brand24.jpg' },
  { id: '25', name: 'Brand 25', image: '/images/brands/brand25.jpg' },
  { id: '26', name: 'Brand 26', image: '/images/brands/brand26.jpg' },
  { id: '27', name: 'Brand 27', image: '/images/brands/brand27.jpg' },
  { id: '28', name: 'Brand 28', image: '/images/brands/brand28.jpg' },
  { id: '29', name: 'Brand 29', image: '/images/brands/brand29.jpg' },
  { id: '30', name: 'Brand 30', image: '/images/brands/brand30.jpg' },
  { id: '31', name: 'Brand 31', image: '/images/brands/brand31.jpg' },
  { id: '32', name: 'Brand 32', image: '/images/brands/brand32.jpg' },
  { id: '32', name: 'Brand 32', image: '/images/brands/brand33.jpg' },
];